### ISSUE TITLE
R training - 2018 Dec 13

### ISSUE THREAD

**Issue by luizaandrade** [worldbank/dime-r-training#21]

**Comment by kbjarkefur** [comment]
Important to talk about projection and two data types, but do have it the first thing. It just throw people off. Have them open a data set thirst so that the participants have something tangible on their computer, before talking about abstract things

**Comment by kbjarkefur** [comment]
Go through a bit of terminology. I think some people were in this class to learn R, and I am not sure if all of them knew topics like:

- spatial analysis - explain that it is analysis of mapped data
- polygons

---
Since some parts so heavily depend on `ggplot` maybe it is worth doing a quick recap. Maybe just remind people that it is a graphing tool, and perhaps remind them of an option or two there

**Comment by kbjarkefur** [comment]
add *worldbank_projects.csv* data to repository

**Comment by luizaandrade** [comment]
Add a first slide explaining where the data is and telling people to load/install packages and set file paths

**Comment by luizaandrade** [comment]
Possibility: Make this a session about data visualization on maps:
- Move parts about raster to appendix
- Move parts about processing shapefiles to appendix
- Present it right after the ggplot session, since it has a lot of related content

**Comment by MRuzzante** [comment]
It would be nice to store every map which is plotted in an object (say `map_11, `map_2`, etc.) consistently with what @luizaandrade did in Lab 3, so people can then print all of them and see what was done in the training

**Comment by MRuzzante** [comment]
Also, you could add some "bonus track" at the end (can be appendix) on embedding `leaflet` in a Shiny app
