### ISSUE TITLE
R training-Intro to R

### ISSUE THREAD

**Issue by MariaArnalCanudo** [worldbank/dime-r-training#40]
- [x] Slide 12: Open datasets from the environment window

- [x] Slide 31: include matrix and array as type of objects 

- [x] Slide 55: R for data science as resource https://r4ds.had.co.nz/

**Comment by luizaandrade** [comment]
1. On slide 12, do you mean click on a data set instead of using View()? I think that is great, and should definitely be added if it's not there. But if you mean load a data set from the computer, that's something that only works if you're setting the working directory, or using projects. That's a problem for us, because we store data sets and code in separate folders, so we prefer using code and objects to do it.

2. not sure we are looking at the same version of the training? In the master branch, R objects are in slide 31. Matrices are in the appendix because we don't use them as much, so we decided to take them out of the main presentation to save time. But I think it's worth adding arrays to the appendix as well.

3. It's on useful resources in the appendix, but without the link. Would be great to add the link as well.
