### ISSUE TITLE
May 2022 - Intro to R Programming

### ISSUE THREAD

**Issue by luizaandrade** [worldbank/dime-r-training#94]
- [x] The exercise to create a project was a bit confusing. It wasn't clear where to create the project and what name it should have. I believe it would be easier to first download the materials and then create the project on an existing folder

**Comment by RRMaximiliano** [comment]
Col means - Slide 57

**Comment by luisesanmartin** [comment]
using pipes in the last exercise added confusion. Don't suggest participants to use pipes here, but if there's time this can be explained in the code snippet after it

**Comment by luisesanmartin** [comment]
for this session and session 1, in the last editions of the course we had to rush in the last 30 minutes because we were running out of time to cover everything. A better methodology would be to not leave time for participants to solve exercises on their own, but always to follow along with the presenter

**Comment by luisesanmartin** [comment]
move data exploration and script sections to the annex so there's more time for apply and custom functions

**Comment by luisesanmartin** [comment]
between sessions 1 and 2, ask them to install all the packages necessary for the course. Include different instructions (like #36 ) for Macs
